<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                <h2 class="mb-5 text-center"><b>TITULO I DISPOSICIONES GENERALES</b></h2>
                <p>ART. 1 EL PRESENTE REGLAMENTO ES DE OBSERVANCIA GENERAL Y OBLIGATORIA PARA LA COMUNIDAD AFODEMY, PERSONAL ADMINISTRATIVO, DOCENTE Y ALUMNADO. CORRESPONDE A LA JUNTA DIRECTIVA SU APROBACIÓN O MODIFICACIÓN EN CASO DE REQUERIRSE. SE REGIRÁ BAJO LOS PRINCIPIOS DE ÉTICA, PROFESIONALISMO, HUMANISMO, INCLUSIÓN, RESPETO Y TOLERANCIA, COMPROMISO, RESPONSABILIDAD Y APEGO A LA CIENCIA.</p>
                <p>ART. 2 AFODEMY ES UNA EMPESA DE CAPACITACIÓN Y DESARROLLO, CONSTITUIDO COMO SOCIEDAD CIVIL CONFORME A DERECHO, QUE TIENE POR OBJETO LA PRESTACIÓN DE SERVICIOS DE ENSEÑANZA, CAPACITACIÓN, ENTRENAMIENTO, CONSULTORÍA, PREPARACIÓN EVALUACIÓN Y DESARROLLO DE PROGRAMAS E IMPARTICIÓN DE CLASES, CURSOS, DIPLOMADOS, SEMINARIOS, CONFERENCIAS, Y EN GENERAL TODO TIPO DE TRANSMISIÓN DE CONOCIMIENTOS DE CUALQUIER TIPO, EN ESPECIAL EN LAS ÁREAS PENALES, ESTUDIO DE LA CRIMINOLOGÍA, CRIMINALÍSTICA, CIENCIAS SOCIALES, ASÍ COMO CIENCIAS AFINES, A PERSONAS FÍSICAS O MORALES, MEXICANAS O EXTRANJERAS, DENTRO O FUERA DE LA REPÚBLICA MEXICANA, YA SEA A TRAVÉS DE PLATAFORMAS DIGITALES O PRESENCIALMENTE.</p>
                <p>ART. 3 PROPORCIONA ASESORÍA, CONSULTORÍA, CAPACITACIÓN, EVALUACIÓN, CERTIFICACIÓN, INVESTIGACIÓN, ENCUESTAS Y ENSEÑANZA EN GENERAL, A NIVEL DE EDUCACIÓN BÁSICA, MEDIA SUPERIOR, SUPERIOR Y POSGRADOS; EN LA MODALIDAD PRESENCIAL, EN LÍNEA, VIRTUAL Y AUDIOVISUAL YA SEA EN EL SECTOR PÚBLICO O PRIVADO; DESARROLLAR E IMPLEMENTAR PROCESOS DE CERTIFICACIÓN DE COMPETENCIAS PROFESIONALES, LABORALES Y ACADÉMICAS; DESARROLLAR PRODUCTOS DE INVESTIGACIÓN BÁSICA Y AVANZADA VINCULADOS AL ÁMBITO EDUCATIVO, LABORAL, GUBERNAMENTAL, POLÍTICO Y SOCIAL EN GENERAL</p>
                <p>ART. 4 NUESTRA PLATAFORMA EDUCATIVA VIRTUAL, ASÍ COMO NUESTRAS PÁGINAS EN REDES SOCIALES, SON LOS ÓRGANOS OFICIALES DE INFORMACIÓN, DONDE SE COMPARTIRÁ NUESTRO CALENDARIO DE EVENTOS, NUESTROS CONVENIOS FIRMADOS, DIVULGACIÓN DE MATERIAL ACADÉMICO, NOTICIAS RELACIONADAS CON AFODEMY Y DEMÁS INFORMACIÓN QUE SE CONSIDERE PERTINENTE.</p>

                <p>
                    ART. 5 LA OFERTA EDUCATIVA DE AFODEMY CONSTA DE:
                    <ol>
                        <li>CURSOS</li>
                        <li>TALLERES</li>
                        <li>SEMINARIOS</li>
                        <li>CONGRESOS</li>
                        <li>DIPLOMADOS</li>
                        <li>ESPECIALIDADES</li>
                        <li>PREPARATORIA/BACHILLERATO</li>
                        <li>MAESTRÍA</li>
                        <li>DOCTORADO</li>

                    </ol>
                </p>

            </div>
            </div>
        </div>
    </div>
</x-guest-layout>
