---
deployment:
  tasks:
    - export DEPLOY=/home/desarrollo/test.afodemy.com/
    - export FILE=/home/desarrollo/test_afodemy/

    - /bin/cp -R ./ $DEPLOY --exclude public/
    # - /bin/cp -R * --exclude 'index.php' public/ $DEPLOY
    # - /bin/cp -R * --exclude 'public/'  ./ $FILE
