---
deployment:
  tasks:
    - export DEPLOY=/home/desarrollo/user.afodemy.com/
    - export FILE=/home/desarrollo/user_afodemy/

    - /bin/cp -R ./ $FILE
    - /bin/rsync -av --exclude 'index.php' public/ $DEPLOY
