---
deployment:
  tasks:
    - export DEPLOYPATH=/home/desarrollo/test.afodemy.com/
    - export FILEPATH=/home/desarrollo/user_afodemy_files2/

    - /bin/cp -a --exclude 'index.php' public/ $DEPLOYPATH
    - /bin/p -a --exclude '/public/' $FILEPATH

