---
deployment:
  tasks:
    - export DEPLOY=/home/desarrollo/test.afodemy.com/
    - export FILE=/home/desarrollo/user_afodemy_files2/

    - /bin/rsync -av --exclude 'index.php' public/ $DEPLOY
    - /bin/rsync -av --exclude 'public/'  ./ $FILE

