---
deployment:
  tasks:
    - export DEPLOY=/home/desarrollo/user.afodemy.com/
    - export FILE=/home/desarrollo/user.afodemy.com/laravels/

    - /bin/rsync -av --exclude 'index.php' public/ $DEPLOY
    - /bin/rsync -av --exclude 'public/'  ./ $FILE
