---
deployment:
  tasks:
    - export DEPLOY=/home/desarrollo/test3.afodemy.com/
    - export FILE=/home/desarrollo/test_afodemy/





    - /bin/cp -R ./ $FILE
    - /bin/cp -ar --exclude='index.php' public/ $DEPLOY


